name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  list-workspaces:
    runs-on: ubuntu-latest
    name: List workspaces
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: set-matrix
        run: node -e "console.log('::set-output name=matrix::' + JSON.stringify(fs.readdirSync('packages')))"
  test:
    runs-on: ubuntu-latest
    needs: list-workspaces
    strategy:
      matrix:
        workspace: ${{ fromJson(needs.list-workspaces.outputs.matrix) }}
    name: ${{ matrix.workspace }} tests
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm --filter ${{ matrix.workspace }} test
      - name: Collect coverage
        uses: codecov/codecov-action@v4
        if: success()
        with:
          files: ./packages/${{ matrix.workspace }}/coverage/lcov.info
          name: ${{ matrix.workspace }}
          flags: ${{ matrix.workspace }}
