name: Release
on:
  push:
    branches:
      - action
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Create pull request with release changes
        run: pnpm tsm --no-warnings ./packages/ci/src/pr.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
